/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.gumtreediff.cidiff;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LogDifferTest {
    
    @Test void rewriteSimTest() {
        assertEquals(0.0, JobDiffer.rewriteSim("A B C", "A B C D"), 0.001);
        assertEquals(0.666, JobDiffer.rewriteSim("A B C", "A E C"), 0.001);
        assertEquals(0.333, JobDiffer.rewriteSim("A B C", "A E F"), 0.001);
        assertEquals(0.0, JobDiffer.rewriteSim("A B C", "G E F"), 0.001);
    }
}
