/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.gumtreediff.cidiff;

import java.io.IOException;

public class CiDiff {
    public static void main(String[] args) throws IOException {
        String leftLog = "data/1379038139.log.csv";
        String rightLog = "data/1359329694.log.csv";
        JobDiffer.diff(leftLog, rightLog);
    }
}
