name: Benchmark algorithms

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup python dependencies
        run: pip install numpy pandas seaborn matplotlip
      - name: Execute Gradle benchmark
        run: ./gradlew benchmark
      - name: Execute jupyter notebook
        uses: yaananth/run-notebook@v2
        with:
          notebook: "python/benchmark.ipynb"
          isReport: False
      - name: Upload notebook as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: nb-output/benchmark.ipynb
          compression-level: 0