name: Build, Test and Deploy GumTree

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    container: openjdk:17
    steps:
      - name: checkout cidiff
        uses: actions/checkout@v2
      - name: build cidiff
        run: ./gradlew build